# Generated by Django 2.0.2 on 2018-09-11 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
        ('index_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMiddle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_count', models.IntegerField()),
                ('small_price', models.IntegerField(null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_app.TBook')),
            ],
            options={
                'db_table': 'order_middle',
            },
        ),
        migrations.CreateModel(
            name='TOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('status', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 't_order',
            },
        ),
        migrations.CreateModel(
            name='TUadress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('postecode', models.CharField(max_length=10, null=True)),
                ('phone_num', models.CharField(max_length=12, null=True)),
                ('telephone', models.CharField(max_length=13, null=True)),
                ('t_del', models.IntegerField(null=True)),
                ('country', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('district', models.CharField(max_length=20, null=True)),
                ('default', models.SmallIntegerField(null=True)),
                ('blank', models.CharField(max_length=20, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.TUser')),
            ],
            options={
                'db_table': 't_uadress',
            },
        ),
        migrations.AddField(
            model_name='torder',
            name='order_addr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order_app.TUadress'),
        ),
        migrations.AddField(
            model_name='torder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.TUser'),
        ),
        migrations.AddField(
            model_name='ordermiddle',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.TOrder'),
        ),
    ]
