# Generated by Django 2.0.2 on 2018-09-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(db_column='username', max_length=20, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('login_time', models.DateTimeField(null=True)),
                ('salt', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 't_user',
            },
        ),
    ]
