# Generated by Django 2.0.2 on 2018-09-11 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20, null=True)),
                ('parent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index_app.Category')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='TBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_total_count', models.IntegerField(null=True)),
                ('pic_url', models.ImageField(upload_to='pic')),
                ('book_name', models.CharField(max_length=20, null=True)),
                ('author_name', models.CharField(max_length=20, null=True)),
                ('publish_firm', models.CharField(max_length=30, null=True)),
                ('publishing_date', models.DateField(null=True)),
                ('version', models.IntegerField(null=True)),
                ('print_date', models.DateField(null=True)),
                ('print_num', models.IntegerField(null=True)),
                ('isbn', models.IntegerField(null=True)),
                ('font_num', models.BigIntegerField(null=True)),
                ('page_num', models.IntegerField(null=True)),
                ('kaiben', models.IntegerField(null=True)),
                ('paper', models.CharField(max_length=20, null=True)),
                ('pack', models.CharField(max_length=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('dang_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('editor_recommend', models.TextField(null=True)),
                ('content_intro', models.TextField(null=True)),
                ('author_intro', models.TextField(null=True)),
                ('catalogue', models.TextField(null=True)),
                ('media_comments', models.TextField(null=True)),
                ('excerpt', models.CharField(max_length=20, null=True)),
                ('t_delete', models.IntegerField(null=True)),
                ('blank', models.CharField(max_length=20, null=True)),
                ('sale_num', models.IntegerField(default=0)),
                ('sale_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer_score', models.IntegerField(null=True)),
                ('l_vrsion', models.IntegerField(null=True)),
                ('comment_times', models.IntegerField(null=True)),
                ('cate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index_app.Category')),
            ],
            options={
                'db_table': 't_book',
            },
        ),
    ]
